import { useState, useMemo } from 'react'
import Head from 'next/head'
import { dehydrate, useQuery, QueryClient } from 'react-query'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getPokemons, usePokemonsQuery } from '../utils/queries'
import { RandomPokemon } from '../components/random-pokemon/RandomPokemon'


export async function getServerSideProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery('pokemons', getPokemons)

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}


export default function Home() {
  const pokemons = usePokemonsQuery()

  const [ filter, setFilter ] = useState('')

  const filteredPokemon = useMemo(
    () =>
      pokemons.filter(p =>
        p.name.toLowerCase().includes(filter.toLowerCase())
      ),
    [ filter, pokemons ]
  )

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemons</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <RandomPokemon />
      <div>
        <input
          type="text"
          value={filter}
          onChange={e => setFilter(e.target.value)}
          className={styles.search}
        />
      </div>
      {/*<div className={styles.container}>*/}
      {/*  {filteredPokemon.slice(0, 20).map((p) => (*/}
      {/*    <div key={p.id} className={styles.image}>*/}
      {/*      <Image*/}
      {/*        alt={p.name}*/}
      {/*        src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}*/}
      {/*        height={200}*/}
      {/*        width={200}*/}
      {/*        placeholder={'blur'}*/}
      {/*        blurDataURL={'/placeholder.png'}*/}
      {/*      />*/}
      {/*      <h2>{p.name}</h2>*/}
      {/*    </div>*/}
      {/*  ))}*/}
      {/*</div>*/}
      <div className={styles.container}>
        {filteredPokemon.slice(0, 40).map(pokemon => (
          <div className={styles.image} key={pokemon.id}>
            <Link href={`/pokemon/${pokemon.id}`}>
              <a>
                <Image
                  alt={pokemon.name}
                  src={`/${pokemon.image}`}
                  height={200}
                  width={200}
                  placeholder={'blur'}
                  blurDataURL={'/placeholder.png'}
                />
                <h3>{pokemon.name}</h3>
              </a>
            </Link>
          </div>
        ))}
      </div>
    </div>
  )
}
